# This file was generated automatically by Qleany's generator, edit at your own risk! 
# If you do, be careful to not overwrite it when you run the generator again.
set(INTERACTOR_LIST
    root/root_interactor.h
    root/root_interactor.cpp
    root/root_signals.h
    recent_project/recent_project_interactor.h
    recent_project/recent_project_interactor.cpp
    recent_project/recent_project_signals.h
    project/project_interactor.h
    project/project_interactor.cpp
    project/project_signals.h
    global_component/global_component_interactor.h
    global_component/global_component_interactor.cpp
    global_component/global_component_signals.h
    entity_component/entity_component_interactor.h
    entity_component/entity_component_interactor.cpp
    entity_component/entity_component_signals.h
    entity/entity_interactor.h
    entity/entity_interactor.cpp
    entity/entity_signals.h
    entity_field/entity_field_interactor.h
    entity_field/entity_field_interactor.cpp
    entity_field/entity_field_signals.h
    entity_parent/entity_parent_interactor.h
    entity_parent/entity_parent_interactor.cpp
    entity_parent/entity_parent_signals.h
    repository_component/repository_component_interactor.h
    repository_component/repository_component_interactor.cpp
    repository_component/repository_component_signals.h
    repository/repository_interactor.h
    repository/repository_interactor.cpp
    repository/repository_signals.h
    interactor_component/interactor_component_interactor.h
    interactor_component/interactor_component_interactor.cpp
    interactor_component/interactor_component_signals.h
    application_component/application_component_interactor.h
    application_component/application_component_interactor.cpp
    application_component/application_component_signals.h
    application_feature/application_feature_interactor.h
    application_feature/application_feature_interactor.cpp
    application_feature/application_feature_signals.h
    c_r_u_d/c_r_u_d_interactor.h
    c_r_u_d/c_r_u_d_interactor.cpp
    c_r_u_d/c_r_u_d_signals.h
    custom_command/custom_command_interactor.h
    custom_command/custom_command_interactor.cpp
    custom_command/custom_command_signals.h
    custom_d_t_o/custom_d_t_o_interactor.h
    custom_d_t_o/custom_d_t_o_interactor.cpp
    custom_d_t_o/custom_d_t_o_signals.h
    custom_d_t_o_field/custom_d_t_o_field_interactor.h
    custom_d_t_o_field/custom_d_t_o_field_interactor.cpp
    custom_d_t_o_field/custom_d_t_o_field_signals.h
    custom_query/custom_query_interactor.h
    custom_query/custom_query_interactor.cpp
    custom_query/custom_query_signals.h
    d_t_o_component/d_t_o_component_interactor.h
    d_t_o_component/d_t_o_component_interactor.cpp
    d_t_o_component/d_t_o_component_signals.h
    c_q_r_s_component/c_q_r_s_component_interactor.h
    c_q_r_s_component/c_q_r_s_component_interactor.cpp
    c_q_r_s_component/c_q_r_s_component_signals.h
    contracts_component/contracts_component_interactor.h
    contracts_component/contracts_component_interactor.cpp
    contracts_component/contracts_component_signals.h
    presenter_component/presenter_component_interactor.h
    presenter_component/presenter_component_interactor.cpp
    presenter_component/presenter_component_signals.h
    presenter_single/presenter_single_interactor.h
    presenter_single/presenter_single_interactor.cpp
    presenter_single/presenter_single_signals.h
    presenter_list_model/presenter_list_model_interactor.h
    presenter_list_model/presenter_list_model_interactor.cpp
    presenter_list_model/presenter_list_model_signals.h
    front_end_component/front_end_component_interactor.h
    front_end_component/front_end_component_interactor.cpp
    front_end_component/front_end_component_signals.h
)